// AI'm by VNS — qanda.jsx (EN)
// 10 validated GEO/AEO questions — English version

export const qanda = [
  {
    q: "What is AI visibility for small businesses?",
    a: "AI visibility is the ability of a business to appear in answers generated by ChatGPT, Perplexity and Gemini when customers search for products or services in its sector. AI search engines read structured and public web content, not category portals or social media.",
  },
  {
    q: "How does AI'm by VNS improve my visibility on ChatGPT?",
    a: "We build with you a set of 10 questions specific to your sector and area. These measure baseline visibility and drive website optimisation with full schema.org, llms.txt, ai.txt and an automated GEO/AEO blog. As results consolidate, the questions are updated to progressively expand the AI visibility radius. Local foundation questions are always monitored in parallel.",
  },
  {
    q: "How much does improving my business AI visibility cost?",
    a: "We offer three packages: Starter for technical optimisation, Growth with automated blog, quarterly report and corrective actions, Pro with Instagram automation and advanced AI competitor analysis. Contact us for a tailored quote.",
  },
  {
    q: "How quickly are results visible on AI search engines?",
    a: "The first measurable GEO/AEO score improvements typically occur within 4 to 8 weeks after full technical optimisation. The system has been validated on Casa Cavour (Bertinoro, IT) and RAB — Romagna Affitti Brevi.",
  },
  {
    q: "Do AI search engines read my Facebook page or Airbnb profile?",
    a: "No. ChatGPT, Perplexity and Gemini don't read Facebook pages, Instagram profiles, Airbnb listings, Booking.com or Google Business profiles. They read websites with schema.org, llms.txt files and semantic blog text.",
  },
  {
    q: "Do I need an existing website to use AI'm by VNS?",
    a: "No. AI'm by VNS can either optimise an existing website or build a new one optimised for AI search engines, with full schema.org, llms.txt and ai.txt files, and an automated GEO/AEO blog.",
  },
  {
    q: "Does AI'm by VNS operate only in Italy or also in the Netherlands?",
    a: "AI'm by VNS is active in both markets: Italy and the Netherlands. The service is available in English, Italian and Dutch. The operational base is in Nijkerk, NL.",
  },
  {
    q: "What is schema.org and why does it matter for AI visibility?",
    a: "Schema.org is a markup language that lets AI search engines understand who you are, what you do and where you are. Without schema.org your website is anonymous text. AI'm by VNS always implements Organization, Person, FAQPage and BreadcrumbList for every client.",
  },
  {
    q: "What is the llms.txt file and why does my website need it?",
    a: "The llms.txt file tells language model crawlers how to read and interpret your website. Similar to robots.txt for search engines, llms.txt increases the likelihood of being cited in generated answers from ChatGPT and Perplexity.",
  },
  {
    q: "How is my business AI visibility measured?",
    a: "With a score from 0 to 10 per search engine (Perplexity, Gemini, ChatGPT) using 10 questions built together with you for your sector and area. The baseline analysis sets the starting point. As results consolidate, questions are updated to expand the visibility radius. Quarterly analyses always compare the original questions to ensure local foundations remain solid.",
  },
]
